package it.istat.dcit.itc.greg;

import it.istat.dcit.itc.greg.dto.RuleDTO;
import it.istat.dcit.itc.greg.model.Rule;
import it.istat.dcit.itc.greg.service.CheckService;
import it.istat.dcit.itc.greg.service.ParsingService;
import org.junit.Before;
import org.junit.Test;

import javax.script.ScriptException;
import java.io.IOException;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.assertTrue;

/**
 * Test rules
 */
public class CheckValidationTest {

    private CheckService srv;

    private List<Rule> rules;
    private List<String> data;

    private Reader validation;


    @Before
    public void setup()throws IOException, ScriptException  {
        srv = new CheckService();
        rules = new ArrayList<>();
        data = new ArrayList<>();
        validation = ParsingService.parseValidations(CheckValidationTest.class.getResource("/validation.js"));
        //header
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        //oppure
        //data = ParsingService.parse(ParsingServiceTest.class.getResource("/residenziale.csv"));
    }


    @Test
    public void testError110(){
        rules.add(new Rule("110", "checkError110( '[[ABITAZIONI]]','[[STANZE]]','[[ACCESSORI]]','[[PIANI]]','[[VOLUME]]','[[SUP_TOTALE]]','[[SUP_UTILE]]','[[SUP_ESTERNI]]','[[SUP_AGRICOLTURA]]','[[SUP_INDUSTRIA]]','[[SUP_COMMERCIO]]','[[SUP_SERVIZI]]','[[SUP_ALTRO]]','[[TOTALE_SUPERFICE]]','[[S1_45]]','[[S2_45]]','[[S3_45]]','[[S4_45]]','[[S5_45]]','[[S6_45]]','[[S1_75]]','[[S2_75]]','[[2.7.31]]','[[S4_75]]','[[S5_75]]','[[S6_75]]','[[S1_110]]','[[S2_110]]','[[S3_110]]','[[S4_110]]','[[S5_110]]','[[S6_110]]','[[S1_O110]]','[[S2_O110]]','[[S3_O110]]','[[S4_O110]]','[[S5_O110]]','[[S6_O110]]','[[TOTALE_TABELLA]]','[[SOPRAELE]]','[[VOLUME_AMP]]','[[SUP_TOTALE_AMP]]','[[ABITAZIONI_AMP]]','[[STANZE_AMP]]','[[ACCESSORI_AMP]]','[[SUP_UTILE_AMP]]','[[STANZE_AMP2]]','[[ACCESSORI_AMP2]]','[[SUP_UTILE_AMP2]]','[[SUP_ESTERNI_AMP]]','[[SUP_PRODUTTIVO_AMP]]','[[NUOVO_AMPLI_COL]]','[[PIANI_COL]]','[[VOLUME_COL]]','[[SUP_TOTALE_COL]]','[[SUP_NONRES_COL]]' )", "",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|21|22|23|||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Error 110 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testError120(){
        rules.add(new Rule("120", "checkError120( '[[ABITAZIONI]]','[[STANZE]]','[[ACCESSORI]]','[[PIANI]]','[[VOLUME]]','[[SUP_TOTALE]]','[[SUP_UTILE]]','[[SUP_ESTERNI]]','[[SUP_AGRICOLTURA]]','[[SUP_INDUSTRIA]]','[[SUP_COMMERCIO]]','[[SUP_SERVIZI]]','[[SUP_ALTRO]]','[[TOTALE_SUPERFICE]]','[[S1_45]]','[[S2_45]]','[[S3_45]]','[[S4_45]]','[[S5_45]]','[[S6_45]]','[[S1_75]]','[[S2_75]]','[[2.7.31]]','[[S4_75]]','[[S5_75]]','[[S6_75]]','[[S1_110]]','[[S2_110]]','[[S3_110]]','[[S4_110]]','[[S5_110]]','[[S6_110]]','[[S1_O110]]','[[S2_O110]]','[[S3_O110]]','[[S4_O110]]','[[S5_O110]]','[[S6_O110]]','[[TOTALE_TABELLA]]','[[SOPRAELE]]','[[VOLUME_AMP]]','[[SUP_TOTALE_AMP]]','[[ABITAZIONI_AMP]]','[[STANZE_AMP]]','[[ACCESSORI_AMP]]','[[SUP_UTILE_AMP]]','[[STANZE_AMP2]]','[[ACCESSORI_AMP2]]','[[SUP_UTILE_AMP2]]','[[SUP_ESTERNI_AMP]]','[[SUP_PRODUTTIVO_AMP]]','[[NUOVO_AMPLI_COL]]','[[PIANI_COL]]','[[VOLUME_COL]]','[[SUP_TOTALE_COL]]','[[SUP_NONRES_COL]]' )", "",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Error 120 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testError130(){
        rules.add(new Rule("130", "checkError130('[[MESE_RILASCIO]]','[[ANNO_RILASCIO]]','[[MESE_RITIRO]]','[[ANNO_RITIRO]]')", "",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|3|2004|6|2007|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO||2004|6|2007|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Error 130 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testError140(){
        rules.add(new Rule("140", "checkError140('[[ANNO_RITIRO]]')", "",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|3|2004|6|2007|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO||2004|6|2017|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Error 140 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testError200(){
        rules.add(new Rule("200", "checkError200( '[[ABITAZIONI]]','[[STANZE]]','[[ACCESSORI]]','[[PIANI]]','[[VOLUME]]','[[SUP_TOTALE]]','[[SUP_UTILE]]','[[SUP_ESTERNI]]','[[SUP_AGRICOLTURA]]','[[SUP_INDUSTRIA]]','[[SUP_COMMERCIO]]','[[SUP_SERVIZI]]','[[SUP_ALTRO]]','[[TOTALE_SUPERFICE]]','[[S1_45]]','[[S2_45]]','[[S3_45]]','[[S4_45]]','[[S5_45]]','[[S6_45]]','[[S1_75]]','[[S2_75]]','[[2.7.31]]','[[S4_75]]','[[S5_75]]','[[S6_75]]','[[S1_110]]','[[S2_110]]','[[S3_110]]','[[S4_110]]','[[S5_110]]','[[S6_110]]','[[S1_O110]]','[[S2_O110]]','[[S3_O110]]','[[S4_O110]]','[[S5_O110]]','[[S6_O110]]','[[TOTALE_TABELLA]]')", "",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|450|450||210|103|||TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|110|||210|103|||TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Error 200 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testError210(){
        rules.add(new Rule("210", "checkError210( '[[ABITAZIONI]]','[[STANZE]]','[[ACCESSORI]]','[[PIANI]]','[[VOLUME]]','[[SUP_TOTALE]]','[[SUP_UTILE]]','[[SUP_ESTERNI]]','[[SUP_AGRICOLTURA]]','[[SUP_INDUSTRIA]]','[[SUP_COMMERCIO]]','[[SUP_SERVIZI]]','[[SUP_ALTRO]]','[[TOTALE_SUPERFICE]]','[[S1_45]]','[[S2_45]]','[[S3_45]]','[[S4_45]]','[[S5_45]]','[[S6_45]]','[[S1_75]]','[[S2_75]]','[[2.7.31]]','[[S4_75]]','[[S5_75]]','[[S6_75]]','[[S1_110]]','[[S2_110]]','[[S3_110]]','[[S4_110]]','[[S5_110]]','[[S6_110]]','[[S1_O110]]','[[S2_O110]]','[[S3_O110]]','[[S4_O110]]','[[S5_O110]]','[[S6_O110]]','[[TOTALE_TABELLA]]')", "",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|21|STANZE|ACCESSORI|140|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|21|STANZE|ACCESSORI|110|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Error 210 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testError400() {
        rules.add(new Rule("400", "checkError400('[[NUOVO_AMPLI_COL]]','[[PIANI_COL]]','[[VOLUME_COL]]','[[SUP_TOTALE_COL]]','[[SUP_NONRES_COL]]')", "",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|3|2004|6|2007|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|3|2004|6|2007|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Error 210 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testError410() {
        rules.add(new Rule("410", "checkError410('[[NUOVO_AMPLI_COL]]','[[PIANI_COL]]','[[VOLUME_COL]]','[[SUP_TOTALE_COL]]','[[SUP_NONRES_COL]]')", "",false));
        // TODO checkError410
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|3|2004|6|2007|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|3|2004|6|2007|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Error 210 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testError420() {
        rules.add(new Rule("420", "checkError420('[[NUOVO_AMPLI_COL]]','[[PIANI_COL]]','[[VOLUME_COL]]','[[SUP_TOTALE_COL]]','[[SUP_NONRES_COL]]')", "",false));
        // TODO checkError420
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|3|2004|6|2007|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|3|2004|6|2007|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO||||||||||||||||||||||||||||||||||||||||||||||||||||1|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Error 210 result should not be emtpy", results.size() == 1 );
    }


    @Test
    public void testError430() {
        rules.add(new Rule("430", "checkError430('[[NUOVO_AMPLI_COL]]','[[PIANI_COL]]','[[VOLUME_COL]]','[[SUP_TOTALE_COL]]','[[SUP_NONRES_COL]]')", "",false));
        // TODO checkError430
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Error 210 result should not be emtpy", results.size() == 1 );
    }



    @Test
    public void testCorrection10(){
        rules.add(new Rule("10", "checkCorrection10('[[ANNO_RITIRO]]')", "getCorrection10Action()", false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|2016|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|2006|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Rule 10 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testCorrection20(){
        rules.add(new Rule("20", "checkCorrection20('[[ANNO_RITIRO]]')", "getCorrection20Action()", false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|2002|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|2020|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Rule 20 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testCorrection30(){
        rules.add(new Rule("30", "checkCorrection30('[[ANNO_RITIRO]]','[[MESE_RITIRO]]')", "getCorrection30Action()", false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|1|2017|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|16|2017|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Rule 30 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testCorrection100(){
        rules.add(new Rule("100", "checkCorrection100('[[MESE_ELABORAZIONE]]','[[ANNO_ELABORAZIONE]]')", "getCorrection100Action('[[MESE_RITIRO]]','[[ANNO_RITIRO]]')", false));
        // correct
        data.add("1|2017|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|1|2017|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("z||TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|1|2017|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Rule 100 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testCorrection110(){
        rules.add(new Rule("110", "checkCorrection110('[[MESE_ELABORAZIONE]]','[[ANNO_ELABORAZIONE]]')", "getCorrection110Action()",false));
        // correct
        data.add("1|2016|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("81|2082|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Rule 110 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testCorrection140(){
        rules.add(new Rule("140", "checkCorrection140('[[MESE_RILASCIO]]','[[ANNO_RILASCIO]]','[[MESE_RITIRO]]','[[ANNO_RITIRO]]')", "getCorrection140Action('[[TITOLO]]','[[MESE_RITIRO]]','[[ANNO_RITIRO]]')",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|5|2017|6|2017|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|2|NUM_PERMESSO|3|2018|6|2017|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|2|NUM_PERMESSO|3|2018|1|2017|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Rule 140 result should not be emtpy", results.size() == 2 );
    }

    @Test
    public void testCorrection150(){
        rules.add(new Rule("150", "checkCorrection150('[[MESE_RILASCIO]]','[[ANNO_RILASCIO]]','[[MESE_RITIRO]]','[[ANNO_RITIRO]]')", "getCorrection150Action('[[MESE_RITIRO]]','[[ANNO_RITIRO]]')",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Rule 150 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testCorrection160(){
        rules.add(new Rule("160", "checkCorrection160()", "getCorrection160Action()",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|TITOLO|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|TITOLARE|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Rule 160 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testCorrection370(){
        rules.add(new Rule("370", "checkCorrection370('[[TITOLARE]]','[[TITOLO]]')", "getCorrection370Action()",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|3|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|1|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|3|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL||CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Rule 370 result should not be emtpy", results.size() == 1 );
    }

    @Test
    public void testCorrection380(){
        rules.add(new Rule("380", "checkCorrection380('[[TITOLARE]]','[[TITOLO]]')", "getCorrection380Action()",false));
        // correct
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|1|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL|1|CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        // wrong
        data.add("MESE_ELABORAZIONE|ANNO_ELABORAZIONE|2|NUM_PERMESSO|MESE_RILASCIO|ANNO_RILASCIO|MESE_RITIRO|ANNO_RITIRO|SEZIONE|COD_PRO|COD_COM|FOGLIO|PARTICELLA|SUBALT|DURATA|PROGRESSIVO|ABITAZIONI|STANZE|ACCESSORI|PIANI|VOLUME|SUP_TOTALE|S1_45|S5_45|2.7.31|S1_110|S5_110|S3_O110|S2_45|S6_45|S4_75|S2_110|S6_110|S4_O110|S3_45|S1_75|S5_75|S3_110|S1_O110|S5_O110|S4_45|S2_75|S6_75|S4_110|S2_O110|S6_O110|TOTALE_TABELLA|SUP_UTILE|SUP_ESTERNI|SUP_AGRICOLTURA|SUP_INDUSTRIA|SUP_COMMERCIO|SUP_SERVIZI|SUP_ALTRO|TOTALE_SUPERFICE|SOPRAELE|VOLUME_AMP|SUP_TOTALE_AMP|ABITAZIONI_AMP|STANZE_AMP|ACCESSORI_AMP|SUP_UTILE_AMP|STANZE_AMP2|ACCESSORI_AMP2|SUP_UTILE_AMP2|SUP_ESTERNI_AMP|SUP_PRODUTTIVO_AMP|NUOVO_AMPLI_COL|PIANI_COL|VOLUME_COL|SUP_TOTALE_COL|SUP_NONRES_COL||CONS_ENERGETICO|RAPP_FORMA|PIANO_CASA");
        Map<String, List<RuleDTO>> results  = srv.performCheck(data, rules, validation, null);
        assertTrue("Rule 380 result should not be emtpy", results.size() == 1 );
    }

}
